### ISSUE TITLE
fix STA provider tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1165]
**Description**
CI tests fail based on intermittent failures on the [STA provider](https://github.com/geopython/pygeoapi/blob/master/tests/test_sensorthings_provider.py) tests.

**Steps to Reproduce**
[example](https://github.com/geopython/pygeoapi/actions/runs/4347068418/jobs/7593930348) 

**Expected behavior**
passing CI

**Screenshots/Tracebacks**

**Environment**
 - OS: any
 - Python version: 3
 - pygeoapi version: master

**Additional context**

**Comment by justb4** [comment]
Yes, just two tests, some number asserts. Had to fix this to get clean build in #1155. Maybe should have opened PR but fix (2x) [was very trivial](https://github.com/geopython/pygeoapi/pull/1155/commits/78979ddba6c0c389a05a1645f42294329ca6f0ea). So hopefully #1155 is merged this week otherwise just fix here.
