### ISSUE TITLE
URL pointing at ogcapi records schema is broken

### ISSUE THREAD

**Issue by drnextgis** [geopython/pygeoapi#1304]
https://github.com/geopython/pygeoapi/blob/44768fc4882b09021e7d45cb62ff7b50b9f3354c/pygeoapi/openapi.py#L64

**Comment by tomkralidis** [comment]
Not all OpenAPI YAML schema definitions in `pygeoapi/openapi.py` currently point to a single bundle/file.

**Comment by drnextgis** [comment]
I noted this. This URL for example is pointing at a web page:

https://github.com/geopython/pygeoapi/blob/2def8e5e470eb3628c71457ea5f03e091252681f/pygeoapi/openapi.py#L65

but the `oapir` URL returns 404, is that expected?

**Comment by tomkralidis** [comment]
Yes, this is expected.  When OGC API - Records is formally published as 1.0, we will point to the bundle YAML file which would be made available at https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/ogcapi-records-1.yaml (URL does not exist yet), for example.

**Comment by drnextgis** [comment]
Is it possible to use the following URL for now: https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/ogcapi-records-1.yaml?

**Comment by tomkralidis** [comment]
The URL at https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/ogcapi-records-1.yaml would return the YAML schema in a GitHub UI.  pygeoapi requires and uses the raw OpenAPI YAML in order to create a valid and fulsome OpenAPI document.

For example, the OpenAPI document (generated via `pygeoapi openapi generate`) as part of the [pygeoapi master branch demo](https://demo.pygeoapi.io/master/openapi?f=json) demonstrates how the various YAMLs from OGC are used and referenced.

**Comment by drnextgis** [comment]
I see, then https://raw.githubusercontent.com/opengeospatial/ogcapi-records/master/core/openapi/ogcapi-records-1.yaml?

**Comment by tomkralidis** [comment]
Yes, however this is not final and there are other artifacts in various files in the working repository that are used.
