### ISSUE TITLE
Add algorithm that transforms files into gdal/ogr objects on the fly

### ISSUE THREAD

**Issue by IngenieroGeomatico** [geopython/pygeoapi#1397]
To optimize processes in OGCAPI - Processes I have developed an algorithm that transforms files on the fly into gdal/ogr objects in a local environment and another that transforms GDAL/OGR objects into the output format.

Thus, the process geo-algorithms always use GDAL/OGR objects and abstracts the developer from reprogramming the data entry for each published algorithm.

I add an example of the simplified code:

("dato" is a file that is published on an HTTP server or a string file)

`

    def leerCapaVectorial(dato, capa = None, EPSG_Entrada = None):

        ogr.UseExceptions()

        inDataSource = ogr.Open(dato)

        if capa == None: 
            capa = inDataSource.GetLayerByIndex(0).GetName()
        
        lyr = inDataSource.GetLayer(capa)
        

        #create an output datasource in memory
        outdriver=ogr.GetDriverByName('MEMORY')
        outDataSource=outdriver.CreateDataSource('memData')

        #copy a layer to memory
        outLayer=outDataSource.CopyLayer(inDataSource.GetLayer(capa),capa,['OVERWRITE=YES'])
        
        return outDataSource
`

Would it be interesting to make a pull request with this development? I think it could be interesting for both Processes and Join

**Comment by ricardogsilva** [comment]
just my two cents:

Unfortunately I do not agree with this proposal since it would mean pygeoapi would have the GDAL bindings as a hard requirement. I think this is not ideal for the following reasons:

- pygeoapi currently uses [rasterio](https://rasterio.readthedocs.io/en/stable/) for some of its core providers. Rasterio provides an alternative binding to GDAL and [is not really compatible with the standard GDAL Python bindings](https://rasterio.readthedocs.io/en/stable/topics/switch.html) - so if pygeoapi were to switch from rasterio it means we would need to re-implement the current functionality in the standard GDAL bindings - to me this seems like a lot of work for little practical gain;

- in the context of OGC API Processes there are many possibilities for implementation of each process (for example, a process may not need to perform any local geospatial operation because it is running on a remote machine). So in my opinion we should not assume local execution with GDAL as the underlying library;

**Comment by IngenieroGeomatico** [comment]
ooooh :(

It's a shame, but I understand your arguments. I hope to be able to contribute another time. Greetings and thank you very much for the response.

**Comment by ricardogsilva** [comment]
@IngenieroGeomatico 

Please don't feel discouraged, I'm sure you'll have other great ideas for us to discuss :sunglasses:  - thank you for the input!
