### ISSUE TITLE
Support data return for STAC collections

### ISSUE THREAD

**Issue by amsnyder** [geopython/pygeoapi#1409]
**Problem**
Apologies if I get some of the terminology wrong here - I'm only a little bit familiar with pygeoapi. I am working on integrating a STAC catalog into a pygeoapi instance as a Hateoas provider. It seems that the pygeoapi endpoints do not return collection data in json format and cannot render a data viewing page (like the one below); the data **only** seems to be returned for STAC items.
![MicrosoftTeams-image](https://github.com/geopython/pygeoapi/assets/30877272/49cb2298-5d9f-4117-aea7-daff52a5cf91)

**Requested Solution**
We would also like this type of view to be available for STAC collections.

**Reasoning**
We are treating a STAC collection as equivalent to a "dataset", and we want to use STAC collections to catalog zarr stores or collections of netcdfs that will be used collectively. We would like to have this same sort of dataset landing page for these STAC collections.

In our implementation of a STAC catalog, collections will either have:
- no child STAC items and (at least) one asset attached to the collection (the top level directory for a zarr store or a single netcdf, if the "dataset" is fully represented by one netcdf)
- several child STAC items (if there are multiple file-like objects that make up the "dataset" - e.g. satellite imagery contained in tifs that cover different spatial extents or a set of netcdfs with one netcdf representing each time step of the dataset), with each item having an asset attached to it that points to a file that is part of the "dataset" represented in the collection.

This seems to be the suggested way to catalog zarrs, as indicated by STAC in their [collection spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md):
![MicrosoftTeams-image (1)](https://github.com/geopython/pygeoapi/assets/30877272/72b675c5-2c28-4ebf-b7c2-fa30523e0716)

And I believe it is also the way Microsoft Planetary computer is cataloging zarrs and netcdfs with STAC, from what I gathered in [this thread](https://discourse.pangeo.io/t/stac-and-earth-systems-datasets/1472/19).

This allows something like a zarr store to be cataloged at the same level as a collection of satellite imagery, like Landsat.

**Related issue** #221

**Comment by amsnyder** [comment]
I think this may be the same as #896 - but I'm not totally sure if these issues are the same or just related.

**Comment by aufdenkampe** [comment]
@sjordan29 & @xaviernogueira, can the two of you look at this issue and brainstorm potential approaches to support this use case?

**Comment by sjordan29** [comment]
I have developed a basic working model to resolve this issue in the [stac-collection-support branch](https://github.com/LimnoTech/pygeoapi/tree/stac-collection-support) of LimnoTech's fork. This solve looks to see if there are any items below a collection, and if not, it renders a similar data viewing page as it would for assets. Thoughts on this solution? 
![image](https://github.com/geopython/pygeoapi/assets/32182441/ca3c94b2-c102-4c7f-bbd8-0ee6ef26822f)

I do not leverage [PySTAC](https://pystac.readthedocs.io/en/stable/) since the original Hateoas does not - perhaps to avoid additional dependencies. I'd think leveraging PySTAC might simplify the code, but at the expense of adding this dependency. 

@ptomasula, would you be willing to look at the [failed test](https://github.com/LimnoTech/pygeoapi/actions/runs/7340294471/job/19986079595)? Do you have any thoughts on why these changes might result in an error with Starlette's slash tests?

**Comment by xaviernogueira** [comment]
@sjordan29 this hit my email. One thing if you don't want to add PySTAC, but do want additional control, you can use stac-pydantic. Basically a library from the STAC people themselves with the schemas. But idk if Pydantic is already a dependency.

**Comment by sjordan29** [comment]
Thanks @xaviernogueira - looks like Pydantic is already a dependency so I'll check that out!
