### ISSUE TITLE
html display does not show prev-next page (anymore)

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#1703]
this came up during tartu workshop

the buttons to navigate to previous next page of item hits seems unavailable

**Comment by webb-ben** [comment]
Note: This is an artifact of the CSV provider, not the HTML template. 

You'll notice this produces a different numberMatched depending on the number of features returned:

https://demo.pygeoapi.io/master/collections/obs/items?f=json&limit=1

https://demo.pygeoapi.io/master/collections/obs/items?f=json&limit=10

The challenge is that pygeoapi determines if it needs to generate next links if the numberReturned does not match the numberMatched (i.e more results to return). 

The html templates work just fine for other providers:

https://demo.pygeoapi.io/master/collections/lakes/items

The issue is that the CSV provider just returns the number of features. Still something worth fixing, but not in the HTML templates.

https://github.com/geopython/pygeoapi/blob/cbab803c0da0c5cd4c02090bb8c5c89950372283/pygeoapi/provider/csv_.py#L173

**Comment by pvgenuchten** [comment]
Thank you @webb-ben for checking, we noticed the behavior also on wfs facade

**Comment by webb-ben** [comment]
You'll notice this is also because of the `numberMatched` / `numberReturned` except the OGR provider does not include either of these values in the response:

[https://demo.pygeoapi.io/master/collections/dutch_castles/items?f=json&limit=1](https://demo.pygeoapi.io/master/collections/dutch_castles/items?f=json)

**Comment by tomkralidis** [comment]
FYI I've updated the CSV provider in #1710 to reflect an accurate `numberMatched` value (albeit at a performance hit, but the CSV provider is mostly for reference anyway, so +1 for completeness/accuracy here).

For OGR-based functionality, we should continue this discussion in #1658
