### ISSUE TITLE
EDR HTML View should offer more information 

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1733]
**Is your feature request related to a problem? Please describe.**
The EDR HTML experience is confusing and hard to navigate. To reach a subsequent "view" the user must click on a link, then ex-post facto enter the `bbox`to render anything with a 200 HTTP status. The `parameter-name` query argument options are present in the JSON response, but there is nothing apparent in any of the HTML views as to what parameters exist for a given EDR collection.

**Describe the solution you'd like**
Either an EDR specific view in the default templates that includes a table of parameters.

**Describe alternatives you've considered**

**Additional context**

**Comment by tomkralidis** [comment]
bbox: This is rooted in the fact that EDR queries always need extra parameters (beyond the endpoint per se) to operate, unlike the other OGC API standards (i.e. `.../items` or `.../coverage` without query parameters would usually return a data payload, unless a service provider chooses to constrain, which they can choose to do in the pygeoapi sense with a custom plugin).

So this means any EDR query link in a pygeoapi collection response will always yield a 400 because of missing required parameters.  I'm not sure how much more we should do in pygeoapi's HTML to combat this.

Having said this, #1736 adds parameter names in HTML.
