### ISSUE TITLE
Expanding api.py with custom functions

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeoapi#203]
Feature request: capability to add user-provided functions to api.py residing outside api.py

Use case: adding api functions that differ from existing api.py functions and which are not a component of the OGC API family, but which would leverage and comply with the pygeoapi codebase

**Comment by jorgejesus** [comment]
@alexandreleroux Could you be more clear with a more concrete functionality/example?

**Comment by tomkralidis** [comment]
If here we mean hosting various endpoints (which are managed outside of pygeoapi) via a single application, this can be accomplished with middleware dispatching at the WSGI level of the application stack, but the other way around.  `pygeoapi/api.py` is a pure Python API, which gets exposed to HTTP via Flask (`pygeoapi/flask_app.py`) or Starlette (`pygeoapi/starlette_app.py` (both of which take care of the actual endpoints).

Example: let's assume you have a WSGI application that is run at `/myapp`, with its own routes/endpoints.   You can attach pygeoapi's WSGI application.  Simple example in Flask:

```python
from werkzeug.middleware.dispatcher import DispatcherMiddleware

from myapp.app import app as app1
from pygeoapi.flask_app import APP as app2

app = DispatcherMiddleware(app1, {'/ogcapi': app2})
```

So any endpoints in `app1` are made available as expected, and any endpoints in app2 (pygeoapi) are made available via `/ogcapi`, `/ogcapi/collections`, and so on.


So instead of extending pygeoapi codebase per se, you would hang pygeoapi's WSGI application off your own which gives you the best of both worlds add custom APIs alongside pygeoapi.

@francbartoli not sure if there's an equivalent in Starlette?

**Comment by francbartoli** [comment]
@tomkralidis if I understand well the problem what we'd like to have is to inject routes into other application at the time when the request is actually performed. Or even better to decouple endpoints for different use cases: OAFeat, OACov, etc.

If this is the goal I guess it is the right moment to consider Dependency Injection as one of the most valid patterns to sort out this kind of problems. FastAPI, based totally on Starlette, has a very detailed explanation about it [https://fastapi.tiangolo.com/tutorial/dependencies/#what-is-dependency-injection](https://fastapi.tiangolo.com/tutorial/dependencies/#what-is-dependency-injection
), in fact, it is extremely easy to achieve that example above with that framework https://fastapi.tiangolo.com/advanced/sub-applications/. This is not supported natively in Starlette but I see tremendous value in it.
However, Starlette has a very well-designed concept of middleware [https://www.starlette.io/middleware/](https://www.starlette.io/middleware/) as well as Flask. In this case, we might want to build our own just in case we'd like to reproducing a Flask behaviour.
