### ISSUE TITLE
Consider bringing blueprints into pygeoAPI for the different features

### ISSUE THREAD

**Issue by jkreft-usgs** [geopython/pygeoapi#301]
**Is your feature request related to a problem? Please describe.**
pygeoAPI is beginning to resemble a swiss army knife- there is OGC API Features, but I'm also seeing STAC over here and OGC Catalogs over there, and there will be more.  There are a few different ways to make sure that it is possible for someone who just wants to spin up the features part doesn't need to worry about the other parts.

**Describe the solution you'd like**
This will probably involve [Flask blueprints](https://flask.palletsprojects.com/en/1.1.x/blueprints/) though there are probably others

**Describe alternatives you've considered**
I haven't thought super hard about this, but I have had to take apart very complex apps after they got complex, and it isn't super fun.

**Comment by tomkralidis** [comment]
cc @francbartoli 

@jkreft-usgs this sounds a bit like #203 . Is there a small example you can point us to in order to demonstrate the concept?

Also, as a rule we keep `pygeoapi.api` as agnostic as possible so that multiple backends are possible (we currently support Flask and Starlette).  Is there a similar concept in Starlette @francbartoli ?

**Comment by francbartoli** [comment]
@tomkralidis I don't think we have something very close to that blueprints in Flask. There is [FastAPI](https://fastapi.tiangolo.com/) which is a framework built on top of Starlette that support the concept of lego but it seems too much overengineering IMHO
