### ISSUE TITLE
implementation of non CRS84 projections on GeoJSON-LD

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#363]
**Is your feature request related to a problem? Please describe.**
@geekdenz  is implementing non CRS84 projection on postgresql data provider, one issue is the representation of non CRS84 data ( e.g EPSG:2193) on GeoJSON-LD that has a specification that doesnt cover this aspect

**Describe the solution you'd like**
Current collection description using `EPSG:2193`  returns:
```
http://localhost:5000/collections/nzlri_land_usage_capability_nztm_limited?f=jsonld
spatial:nul
```
for example on obs
```
 "spatial": [{"@type": "Place", "geo": {"@type": "GeoShape", "box": "-180,-90 180,90"}}],
```

**Describe alternatives you've considered**
GeoJSON-LD doesnt seem to support projection, should the bbox on `EPSG:2193` be converted to CRS84 ??? or some another way to describe data

**Additional context**
This is a discussion ticket

**Comment by alpha-beta-soup** [comment]
It's not so much a GeoJSON-LD issue, but a GeoJSON spec issue in general.

To quote the [RFC 7946](https://tools.ietf.org/html/rfc7946):

> 4.  Coordinate Reference System
> 
>    The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units of decimal degrees.  This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.  In the absence of elevation values, applications sensitive to height or depth SHOULD interpret positions as being at local ground or sea level.
>
> Note: the use of alternative coordinate reference systems was specified in [GJ2008], but it has been removed from this version of the specification because the use of different coordinate reference systems -- especially in the manner specified in [GJ2008] -- has proven to have interoperability issues.  In general, GeoJSON processing software is not expected to have access to coordinate reference system databases or to have network access to coordinate reference system transformation parameters.  However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

This limitation is therefore inherited.

**Comment by alpha-beta-soup** [comment]
With respect to https://schema.org/GeoShape and https://schema.org/box in particular, bear in mind the definition of GeoShape (my emphasis):

> The geographic shape of a place. A GeoShape can be described using several properties whose **values are based on latitude/longitude pairs**. Either whitespace or commas can be used to separate latitude and longitude; whitespace should be used when writing a list of several such points.

**Comment by jorgejesus** [comment]
@alpha-beta-soup  Thank you so much for the indications and quotes,  them (IMHO) shouln't we reproject the data from the `DataProvider` to use lat/long pairs ?

**Comment by alpha-beta-soup** [comment]
To be compliant with RFC7946, yes, we should only output GeoJSON with lat/lon WGS84 coordinates. However I have seen "wild" GeoJSON with coordinate pairs that are projected. If an application can handle the projected coordinates, and knows what the projection is, that doesn't seem egregrious. Apart from it not being in the spec, the other issue comes about when an application does not know in advance what the projection is or could be, and there's no good way to identify the projection (or its units). Then the geometry is as good as useless.

This should not be too surprising: GeoJSON is popular both because of—and despite—it's simplicity. We don't expect GeoJSON to support circles, curves, topology, dates, [styles](https://github.com/mapbox/simplestyle-spec), or [M-values](https://github.com/mapbox/geojson-coordinate-properties), let alone arbitrary CRSs. The specification also *recommends* (but does not *require*) that coordinate precision is limited to 6 decimal places, which is perhaps something else we could consider doing by default, regardless of source.

The Spatial Data on the Web Best Practices document has a lot to say on this:

> When publishing spatial data, it is best to help users avoid the need for them to transform spatial data between coordinate reference systems themselves by providing data in a form, or forms, which they can use directly. To determine which coordinate reference system(s) are needed, data publishers must consider the intended applications of their user community.

So defining a source that's in a weird or local projection, and publishing it as RFC7946 (i.e. WGS84) GeoJSON would be of benefit to many. But that doesn't mean we can't publish it in a different format with the original, or an alternative, projection.

So I think the apropriate thing to do is to allow other formats that do have such a capability to handle server-side reprojection, but expect GeoJSON-consuming clients to do their own reprojection if appropriate.

On that note, (Geo)JSON-LD affords an opportunity to publish *multiple geometries* about the same Thing, allowing geometries to be described using alternative CRSs, as long as the GeoJSON semantics aren't affected.

To take a JSON-LD example from the SDWBP:

```json
{
  "@context": {
    "geosparql" : "http://www.opengis.net/ont/geosparql#" ,
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#" ,
    "asWKT" : {
      "@id" : "http://www.opengis.net/ont/geosparql#asWKT" ,
      "@type" : "geosparql:wktLiteral"
    }
  } ,
  "@id" : "http://example.org/register/id/building/0363100012169587" ,
  "@type" : "http://www.opengis.net/ont/geosparql#Feature" ,
  "rdfs:label" : "Building 0363100012169587" ,
  "geosparql:hasGeometry": {
    "geosparql:asWKT" : "<http://www.opengis.net/def/crs/EPSG/0/4326> 
                        POLYGON ((52.375108 4.884235, 52.375153 4.884276, 
                                  52.375159 4.884257, 52.375254 4.883981, 
                                  52.375109 4.883850, 52.375075 4.883819, 
                                  52.374979 4.884104, 52.374965 4.884143, 
                                  52.375035 4.884207, 52.375016 4.884263, 
                                  52.374996 4.884320, 52.374926 4.884255, 
                                  52.374901 4.884329, 52.375034 4.884451, 
                                  52.375108 4.884235))"
  }
}
```

So we could include both a RFC7946 GeoJSON `geometry` and a `geosparql:asWKT` in the (Geo)JSON-LD response, to be able to support an alternative CRS as output (or because that's the original CRS from the source data).

Output types like GeoPackage can just work around this by supporting whatever CRS they like, it's really only a headache for GeoJSON compliance.

**Comment by alpha-beta-soup** [comment]
https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/#geometry-and-crs

**Comment by geekdenz** [comment]
@alpha-beta-soup and @jorgejesus 
You both raise good points.

I understand that geojson is the format that it is with limited geometric shapes that are basically just polygons with lines. This and the interoperability argument do in fact support that we should just support wgs84.

However, postgis does indeed implement other projection support in its geojson format. This is why I think it is an easy format to support and since probably a lot of software supports this, in practice makes sense to support by pygeoapi as well.

I do suggest though that it should be enforced that wgs84 is the default and everything gets reprojected to that unless the client requests a particular projection.
