### ISSUE TITLE
error message does not respect accept header

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#435]
when running into this error

![image](https://user-images.githubusercontent.com/299829/82131103-0cafde00-97d2-11ea-83b3-0969e7b89126.png)

the response is in json, although the request header was text/html

**Comment by alpha-beta-soup** [comment]
I wonder if it's best to return a 406 Not Acceptable response in these cases? Problem is, that would become quite a misleading output, since the reqeuested Accept header might be feasible, it's just that something else has caused an error, and the error message does not conform to the requested type...

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

> In practice, this error is very rarely used. Instead of responding using this error code, which would be cryptic for the end user and difficult to fix, servers ignore the relevant header and serve an actual page to the user. It is assumed that even if the user won't be completely happy, they will prefer this to an error code.
>
> If a server returns such an error status, the body of the message should contain the list of the available representations of the resources, allowing the user to choose among them.

This then raises the question: "the list of the available representations of the resources" for *the error* or for the *intended resource*? These would very likely be a different set of representations, and returning the former is very misleading.

Given that, I'd suggest keeping the JSON errors as is, with their error-appropriate HTTP statuses, and perhaps including an HTML representation of the various error pages too, but I wouldn't require that error messages strictly respect the Accept header. (I suspect you weren't actually proposing that, I'm just being pedantic.) They can't anyway, e.g. if you request a GeoPackage and there's some error, you can't reasonably expect the error message to be sent back inside a GeoPackage :smile:

**Comment by tomkralidis** [comment]
HTML error responses are now supported.
