### ISSUE TITLE
JSON LD errors in Travis

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#444]
**Description**
For some reason, running tests against `tests/test_api.py` yield errors within the JSON LD tests.

**Steps to Reproduce**
`py.test tests/test_api.py`

**Expected behavior**
Passing tests/no errors

**Screenshots/Tracebacks**
https://travis-ci.org/github/geopython/pygeoapi/jobs/694768368

**Environment**
 - OS: any
 - Python version: 3.6/3.7
 - pygeoapi version: master

**Additional context**
None

**Comment by alpha-beta-soup** [comment]
I suspect it's related to this https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-632227864 (ref. https://github.com/digitalbazaar/pyld/issues/105), i.e. that following a DOS attack, https://schema.org/ was reconfigured and now only returns HTML, rather than the JSON-LD it was once possible to obtain with content negotation at that URI.

Kind of hits at a sore spot for linked data, i.e. the assumption that arbitrary remote URLs will resolve reliably.

> While I regret that this has been inconvenient to various folk, maybe it can help kickstart discussion of robustness in JSON-LD parsing? It is not ideal to have software processes which assume 100% perfect access to remote networked services. At Schema.org we expressed concerns back in 2014 (/cc @rvguha) that
>
> > [...] we do have concerns about the
schema.org website forming an integral part of numerous unknown
software systems and applications. It ought to be possible to do
useful things with schema.org-based json-ld without a dependency on
the Web site.

Fortunately in this case it should just mean updating those links to use https://schema.org/docs/jsonldcontext.jsonld

**Comment by alpha-beta-soup** [comment]
cf https://github.com/digitalbazaar/pyld/issues/128

This keep causing me grief. Tests (with pyld) only work with the full `.jsonld` URL, but the Google Structured Data Testing tool will only work with `https://schema.org`. I think I'd now prefer to fix it upstream than to work around it.

**Comment by tomkralidis** [comment]
Any update on this one?  Should we close?
