### ISSUE TITLE
remove duplicated id

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#453]
This line displays the (internal) id of the feature

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi/templates/items.html#L87

Which in most/all cases is the same value as the field defined in 

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi-config.yml#L117

Which causes a duplication of the id column.

![image](https://user-images.githubusercontent.com/299829/84317377-f09f2280-ab6c-11ea-8406-e486aaf4f4d7.png)

I'm wondering should we remove this line

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi/templates/items.html#L87

Or only show it conditionally for certain providers or if id_field is not provided in

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi-config.yml#L117

**Comment by alpha-beta-soup** [comment]
After looking at https://info.geoconnex.us/collections/hu02/items/09, @dblodgett-usgs it would be good to get your opinion on how IDs (especially HTTP URI IDs) should be treated.

**Comment by dblodgett-usgs** [comment]
I don't think the id field should be duplicated and agree that the id field should have a hyperlink on it that gets you to the item. That issue should be treated separately from canonical URI IDs but there is some overlap in that you may want to override the hyperlink with a URI.

We have this issue: https://github.com/geopython/pygeoapi/issues/433 to handle the canonical URI use case. Thre's a linked issue discussing the issue a bit more here: https://github.com/internetofwater/geoconnex.us/issues/19

@gpetrochenkov-usgs is working on fixing up some of the hacks we put into this fork of pygeoapi: https://github.com/ksonda/pygeoapi

**Comment by alpha-beta-soup** [comment]
![Screenshot from 2020-06-26 13-36-58](https://user-images.githubusercontent.com/5925045/85811431-42bd8600-b7b2-11ea-86c1-9a5a16d8c169.png)
![Screenshot from 2020-06-26 13-37-12](https://user-images.githubusercontent.com/5925045/85811430-418c5900-b7b2-11ea-940c-2e00652b5169.png)

This issue is related to #433, so I'm trying to hit both birds with one stone. Above are some screenshots of my local development instance.

- I've renamed the first column in the item table to `"URI"` and made it so this is always a link.
- If the configuration for a collection has a `uri_field` (top image), then:
  - This will be used as the display value in this table
  - This will be used as the `feature.id` property value for a JSON view
  - This will be used as the JSON-LD `@id` for each item
  - This will be used as the canonical link for an item
- Otherwise (bottom image):
  - The configuration for the collection always has an `id_field` which determines the `itemId` in the pygeoapi path (`{host}/collections/{collectionId}/items/{itemId}`)
  - The URI value in this table will still be a URL, but it will be the automatically-constructed path

This applies to both `/items` (above) and `items/{itemId}` (below).

![Screenshot from 2020-06-26 13-37-41](https://user-images.githubusercontent.com/5925045/85811484-654f9f00-b7b2-11ea-8172-2c6c35ed6a66.png)
![Screenshot from 2020-06-26 13-37-24](https://user-images.githubusercontent.com/5925045/85811489-6680cc00-b7b2-11ea-844c-ef59d71d6a34.png)

The change influences the JSON/JSON-LD representations and embedded links, and even the pop-up content, so it's more than a simple display change.

**Comment by ksonda** [comment]
Is it intended to have no links in the JSON-LD representations but to keep them in the JSON?

``` _data.pop('links', None)``` line 448 of api.py in #469

**Comment by alpha-beta-soup** [comment]
Yes, that's intentional. If you can think of what `links` and the various nested properties should be expanded to, we can put that definition in the default `@context`. Otherwise I didn't see why they should be retained. If you have a reason you need them retained, I'd be interested in hearing it and I'm more than happy to re-consider including the links.

**Comment by ksonda** [comment]
That makes sense. It _maybe_ made sense to keep them (and keep the pygeoapi urls) if whatever PID service people are using can't handle query strings, but I don't know how common that is. 

```
 If you can think of what links and the various nested properties should be expanded to, we can put that definition in the default @context
```This is more of a pipe dream/ brainstorm: in our use case, it would be cool to have some default topological links with geosparql predicates generated between collection items specified in the configuration. Like info.geoconnex.us/collections/gages/ items could have links to the states or watershed they are within. This would be a workaround for the inappropriateness of having arrays of predicates:objects in simple features.  But that is probably well out of scope at this point and we fully intend to make those kinds of links "upstream" of pygeoapi configuration.

**Comment by alpha-beta-soup** [comment]
I would calculate those links "upstream" of pygeoapi, and just publish them as properties. If you use PIDs for referering to other features across collection boundaries, you could calculate those relationships at the database level and pygeoapi would just inherit them as it would any other property. That's essentially what I did for a test/sample case here (but it's not a geosparql spatial predicate): https://github.com/geopython/pygeoapi/pull/246#issuecomment-538186144 e.g. see the `isSampleOf` relationship.

I understand that doesn't solve the case of determining relationships *across collections* (i.e. watersheds within states, and states with watersheds), but pygeoapi is not (and probably will never be) responsible for *calculating* those relationships.

**Comment by dblodgett-usgs** [comment]
Oh wow -- I hadn't seen your PostGresQL complex JSON-LD creation. I like it -- a lot. 

Have you had time to build up any documentation? per: https://github.com/geopython/pygeoapi/pull/246#issuecomment-567492239

I'd be keen to start using this for the work with @ksonda on geoconnex.

**Comment by alpha-beta-soup** [comment]
@dblodgett-usgs The documentation I added is limited to describing how to extend the `@context`, using a CSV as an example: https://docs.pygeoapi.io/en/stable/configuration.html#linked-dataI didn't go into more complex cases like generating JSON/JSON-LD directly with Postgres, since as far as pygeoapi can tell, it's still the same `@context` extension mechanism. If you think such an example would be worthwhile, then I can add that.

**Comment by dblodgett-usgs** [comment]
ehhh... don't sweat it. Now that I understand better what it's doing, I'm not sure I should be the reason you work up documentation.

**Comment by tomkralidis** [comment]
Is this covered now given #676 ?

**Comment by dblodgett-usgs** [comment]
I believe so, yes.
