### ISSUE TITLE
Google doesn't dereference linked JSON-LD context.

### ISSUE THREAD

**Issue by dblodgett-usgs** [geopython/pygeoapi#457]
**Description**
Google doesn't resolve the geojson-ld context.

**Steps to Reproduce**
This resource from the latest pyGeoAPI: https://demo.pygeoapi.io/stable/collections/lakes/items/1

In the google test-tool:

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdemo.pygeoapi.io%2Fstable%2Fcollections%2Flakes%2Fitems%2F1

note Type error

**Expected behavior**
This resource: https://geoconnex.us/ref/hu02/09 from a hacked pygeoapi that has the geojson-ld context inline.

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgeoconnex.us%2Fref%2Fhu02%2F09

note no type error

**Additional context**
Just putting the content of the geojson-ld context in line fixes this issue.

**Comment by alpha-beta-soup** [comment]
That's nice and small, should be fine to inline it. But it's a bit disappointing that it won't dereference remote contexts though... what if they change?

**Comment by dblodgett-usgs** [comment]
I think the "what if they change?" issue goes both ways -- having a context disconnected from the file in question introduces the potential that the remote context could change and break the file in question.

**Comment by pvgenuchten** [comment]
schema.org on collection level is correctly picked up, in the test tool

![image](https://user-images.githubusercontent.com/299829/84549730-06e1e580-ad09-11ea-9cbd-866a7de6df88.png)

also in the search console

![image](https://user-images.githubusercontent.com/299829/84549697-eb76da80-ad08-11ea-856c-9bb590136ec0.png)

I can confirm google test tool fails in parsing https://demo.pygeoapi.io/master/collections/dutch_windmills/items/Molens.1, but i've no idea if that is valid json-ld

**Comment by pvgenuchten** [comment]
mmm, results above may be related to #459, we still have 2 implementations of schema.org on the collections page, and indeed the embedded json-ld seems broken

**Comment by alpha-beta-soup** [comment]
So do we want to remove the microdata and leave all the semantic content up to JSON-LD? It is possible to mix them.

**Comment by dblodgett-usgs** [comment]
Note that because the geojson-ld context isn't resolved, google doesn't recognize any of the json-ld as structured data. If I copy in the geojson-ld context I get:
![Screen Shot 2020-06-15 at 6 45 36 AM](https://user-images.githubusercontent.com/1492803/84653931-ee71f680-aed3-11ea-947a-50505822d89b.png)

**Comment by alpha-beta-soup** [comment]
Is this just a limitation of the Google Structured Data Testing tool?

Do we also need to inline the entire schema.org context vobaculary in order for the schema.org terms to be identified correctly? https://github.com/geopython/pygeoapi/issues/444

Using https://search.google.com/test/rich-results on /collections and /collections/{collectionId} without inlining https://schema.org (or indeed, not even referring to https://schema.org/docs/jsonldcontext.jsonld as in #444 which would be the direct equivalent) and it picks up the https://schema.org/dataset metadata correctly.¹

/collections
![Screenshot from 2020-06-17 13-20-17](https://user-images.githubusercontent.com/5925045/84844093-ca621100-b09d-11ea-90e0-90c4fe4d4294.png)

/collections/nz-residential-areas (from personal configuration)
![Screenshot from 2020-06-17 13-19-27](https://user-images.githubusercontent.com/5925045/84844094-cc2bd480-b09d-11ea-816b-ec37a60a0610.png)

At the level of an individual feature, and *without inlining the GeoJSON vocabularly* the [JSON-LD playground](https://json-ld.org/playground/) correctly identifies the GeoJSON types, where the Google tool does not:

![Screenshot from 2020-06-17 13-28-59](https://user-images.githubusercontent.com/5925045/84844516-a05d1e80-b09e-11ea-92db-a369f4065403.png)

This makes me inclined to think that the root problem is the Google Structured Data Testing tool. Does it require inlining all contexts? 

---

¹ Although some particular datasets error because their descriptions have fewer than 50 characters—a limitation that is not even mentioned in https://schema.org/description, where the sample value has fewer than 50 characters, so this seems to be an additional Google constraint.

**Comment by alpha-beta-soup** [comment]
Incidentally, it's already possible to inline the entire GeoJSON context yourself for each collection, with the configuration collection `context`. It would get placed after the default/mandatory GeoJSON context URL in the generated `@context`, so whether or not it is dereferenced, the outcome should be the same.

**Comment by dblodgett-usgs** [comment]
Good to know about inlining the context in configuration.

It appears that google doesn't look at inline contexts at all.

```
{
  "@context": "https://schema.org/docs/jsonldcontext.json",
  "@id": "https://test",
  "name": "test_name"
}
```

However, it would work to just do:

```
{
  "@context": {
    "schema": "https://schema.org/"
  },
  "@id": "https://test",
  "schema:name": "test_name"
}
```

**Comment by tomkralidis** [comment]
Is this working now given #676 ?

**Comment by dblodgett-usgs** [comment]
Yes. Now that we don't use the geojson-ld context, the by reference issue is gone.
