### ISSUE TITLE
Generate OpenAPI document for CQL extension

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#460]
**Is your feature request related to a problem? Please describe.**
Change the codebase to accomplish the generation of a document accordingly with a modified configuration for the CQL extension 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FarheenB** [comment]
All the feature request follows OGC Standards.
The Section10.3 of http://docs.opengeospatial.org/DRAFTS/19-079.html#cql-json which follows 
**"$schema": "http://json-schema.org/draft-07/schema#"** Is a mismatch with OpenAPI 3.0 specifications.
 
The requirement here is to implements the CQL Filter class so that this requirement shall be able to parse a ﬁlter expression encoded as JSON that validates against the JSON Schema. The reference of all the expressions and operators are described under the “definitions” property like 
**{“$ref”: “#/definitions/intersects”}** 
Though the definitions property was supported in OpenAPI 2.0 as
 ![image](https://user-images.githubusercontent.com/59408650/84579475-ab3c5880-adeb-11ea-862c-34867e313529.png)
![image](https://user-images.githubusercontent.com/59408650/84579483-b1cad000-adeb-11ea-8331-d4b42f9f781c.png)
specified in https://swagger.io/docs/specification/2-0/basic-structure/
 
But in OpenAPI 3.0 version “definitions” are replaced by “components/schemas” property such as
![image](https://user-images.githubusercontent.com/59408650/84579498-c6a76380-adeb-11ea-84a5-7357e41a211b.png)
Specified in https://swagger.io/docs/specification/describing-responses/

Thus an alternative solution considered here is to convert the json document that supported 2.0 to support 3.0.
The proposed json files for [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json) or [filter-capabilities.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/filter-capabilities.json) files are as follows:

[filter-capabilities.txt](https://github.com/geopython/pygeoapi/files/4775507/filter-capabilities.txt)
[cql.txt](https://github.com/geopython/pygeoapi/files/4775508/cql.txt)

And the suggested CQL extension in OpenAPI document to support the 3.0 version can be found at:
https://app.swaggerhub.com/apis/FarheenB/pygeoapi/3.0

Also cannot keep the definitions property directly inside components/schemas 

![image](https://user-images.githubusercontent.com/59408650/84579591-96ac9000-adec-11ea-9f30-3a750acb94ce.png)

as it leads to the following error:

![image](https://user-images.githubusercontent.com/59408650/84579593-9b714400-adec-11ea-9d94-9c50f72e1440.png)

**Comment by francbartoli** [comment]
@FarheenB I thought we already overcame the problem in the previous task by converting jsonschema fragments to openapi. Why do we still need to keep “definitions”?

Let’s move forward and write the test to check if those final fragments from your swagger file are written in the produced openapi document generated by the command line of pygeoapi.

See the test failing and then start to hack pygeoapi codebase to make it passing.

**Comment by FarheenB** [comment]
No am not adding "definitions" in the doc now. Just wanted to update you with this issue.

I will start editing the config file and make changes in openapi.py next to meet the requirements of CQL OpenAPI implemetation.

**Comment by jorgejesus** [comment]
@FarheenB  Give a look at https://github.com/geopython/pygeoapi/issues/450 it has the indication on how you need to do your first development

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus I have created a new branch [GSoC_CQL_farheen)(https://github.com/FarheenB/pygeoapi/tree/GSoC_CQL_farheen) for all my commits related to CQL implementation.

- [CQL_OpenAPI proposed yaml Document](https://github.com/FarheenB/pygeoapi/blob/GSoC_CQL_farheen/cql_openapi_doc.yaml) 
- Modified [openapi.py](https://github.com/FarheenB/pygeoapi/blob/GSoC_CQL_farheen/pygeoapi/openapi.py) file so that it generates the proposed openapi document 
- [example-config.yml](https://github.com/FarheenB/pygeoapi/blob/GSoC_CQL_farheen/example-config.yml) and  [example-openapi.yml](https://github.com/FarheenB/pygeoapi/blob/GSoC_CQL_farheen/example-openapi.yml) (for your reference) files generated in alignment with the proposed document by making changes in openapi.py file

Next, I am working on remaining bullet points posted by @jorgejesus in #450

**Comment by FarheenB** [comment]
Sorry, I got to know about TDD bit late. So here after I will be following it for further development.

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus 
Below are the update on the list of tasks that I did after tomorrow's discussion with @francbartoli:
- Read TDD document
- Snyced my [forked master](https://github.com/geopython/pygeoapi/compare/master...FarheenB:master) with pygeoapi master
- Created a new branch [openapi-cql](https://github.com/FarheenB/pygeoapi/tree/openapi-cql) for CQL OpenAPI implementation
- Added filter key in [pygeoapi-test-config.yml](https://github.com/geopython/pygeoapi/compare/master...FarheenB:openapi-cql#diff-32e6393787b62433deaec3f787478ef3) for cql-text and cql-json
- Added test cases on every piece of the openapi document related to CQL extension in [test_openapi.py](https://github.com/geopython/pygeoapi/compare/master...FarheenB:openapi-cql#diff-bef210239884d892a2f3a407f51a3518)
- Added changes in [openapi.py](https://github.com/geopython/pygeoapi/compare/master...FarheenB:openapi-cql#diff-54faabbceba4c6a3cb0228df30fb5e6a) file for filter, filter-lang, CQL components, responses and schemas

All test cased were passed while executing test_openapy.py:
![image](https://user-images.githubusercontent.com/59408650/85211967-c0753200-b36b-11ea-9161-39c5f3ff53dd.png)

Things need to be discussed :
- If any further enhancement needed in writing test cases

Bug resolved:
- In  [pygeoapi-test-config.yml](https://github.com/geopython/pygeoapi/compare/master...FarheenB:openapi-cql#diff-32e6393787b62433deaec3f787478ef3) file, the data value given for provider CSV is the path to obs.csv file. The path was incorrect instead of test/data/obs.csv it should be data/obs.csv. This fix was needed to run my test cases to generate openapi document. 
- Though a similar fix is needed in [pygeoapi-test-config-envvars.yml](https://github.com/FarheenB/pygeoapi/blob/openapi-cql/tests/pygeoapi-test-config-envvars.yml) file.

**Comment by jorgejesus** [comment]
@FarheenB  Concerning the suggestions (always good to have),  there are some issues.

- pytest should be run from the upper `pygeoapi` folder and not on the test folder (indication the docs https://docs.pygeoapi.io/en/latest/development.html) , and therefore the path to data should be `test/data/obs.csv`.  You roolback or patch the modified files

**Comment by FarheenB** [comment]
@jorgejesus Done..!!
