### ISSUE TITLE
Design the implementation of a DSL for CQL 

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#484]
**Is your feature request related to a problem? Please describe.**

The goal of this macro task is to give a clear understanding of the main points for having a Domain-Specific Language that can interpret, parse and validate the queries from an HTTP request with the CQL filters. Subtasks are:

- [x] Study how to implement a DSL in python. 
- [x] Experiment with the [pycql](https://github.com/geopython/pycql) package
- [x] Basic pytest example code with pycql that validates simple `filter` (can be the logical operators and comparison expressions for obs. eg: `stn_id < 2147 AND id > 377` )
- [x] Draw a design diagram for a CQL class that handles the input filters and turn them into queries for the different backend providers 
- [x] Write unit tests for the CQL class and its methods

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FarheenB** [comment]
@jorgejesus @francbartoli Added my first commit related to pycql extension for providers.

**Files Added:**

- filters.py for defining all the filter evaluating functions and return **filtered features** (only combination and comparison operators definition added till now.. more operators evaluation logics to add... )
- evaluate.py for evaluation of AST and integration of pycql in pygeoapi 

**Files Modified:**

- test_csv__provider.py for unit testing combination and comparison operators. Test successful for `stn_id < 2147 AND id > 377 ` filter expression on test dataset ('pygeoapi-test.csv'). Along with this tested the code for various other filter expression comprising of logical and comparison operators. 
- csv_.py for passing cql filter expression at provider level and generating AST of cql filter expression using *pycql lexer and parser*.


**Topics to discuss on:**

- Regarding a **new PR** for pycql_extension branch, @francbartoli was concerned about us loosing all the conversation. Therefore adding pycql extension code in the existing branch PR. I will squash some of the commits though.
- Code is more specific to **CSVProvider** now. Need to study about other Providers' data generation process, to develop a generic solution for calling cql filter extensions.
-  **Fields and Query** lookups are implemented in each provider separately, so need some insight on how can I make pycql extension code more generic.
- I will add definition for operators like **spatial and temporal** in filters.py. There is need to define their functions in such a way that its accessible by all the providers. Therefore its taking time in implementation.
- After this I will start working on evaluation of **complex filter expressions**.
- I will write more **unit test cases** on filter expressions. Suggest some examples on simple as well as complex filters.
- Suggest **fold structure** for CQL Filter related files.For time being I have added filters.py and evaluate.py in pygeoapi base folder
- According to my understanding and research work I came up with the above committed approach/process flow. Please suggest if there is any alternative that I should consider. 

P.S. The master branch changes are yet to be merged in my forked branch, therefore Travis fail. I will resolve the conflicts and upload again.

![image](https://user-images.githubusercontent.com/59408650/87615905-66c91300-c731-11ea-99ed-2311dec23ad4.png)

**Comment by FarheenB** [comment]
Branch successfully merged with master.

**Comment by FarheenB** [comment]
Resolved changes suggested by @francbartoli

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus 

- Created custom exception classes specific to CQL Filter. [exception.py ](https://github.com/FarheenB/pygeoapi/commit/c4da83b6da6fcf9943120893e6a27e18c4751a91#diff-159713785c1a6ec11702b66f46252c70) file contains all the exception classes used in evaluation of AST of CQL filter expression. I will add more exception classes to it as the implementation of more filter operators are done.
- Also restructured [test_csv__provider.py](https://github.com/FarheenB/pygeoapi/commit/c4da83b6da6fcf9943120893e6a27e18c4751a91#diff-40aebfd484a64027b5f0fb453e1c4c21) and added some unit cases as per the implementation of CQL. Please give it a look.

**Comment by jorgejesus** [comment]
@FarheenB @francbartoli 
- I left some comment on the csv provider concerning generic class structure: https://github.com/FarheenB/pygeoapi/commit/c4da83b6da6fcf9943120893e6a27e18c4751a91#r40772524 . Everything should come from `pygeoapi.evalute` and as classes. Later we could have some class extension/oveload based on provider 
- @FarheenB Spatial/temporal filter, try to implement something general for CSV, we have other providers like `PostgreSQL` that have good spatial/temporal filter and it could be that we have also the possibility to use those functions.

**Comment by FarheenB** [comment]
Open for discussion:

![image (1)](https://user-images.githubusercontent.com/59408650/88368698-3249fc80-cdac-11ea-9860-91456139b074.png)

**Comment by FarheenB** [comment]
@jorgejesus comments:

`The providers are loaded a bit like a plugin, I am tempted to say that CQL should be also a plugin, loaded on the api.py, at the api.py it would make sense for the CQL plugin (with the CQL classes that you made) would validate if the submitted cql_filter is valid in the context that is being called (what queriables we have, and what the provider can do). If the CQL plugin/code determines that the request is not OK, then it raises an error and things don't go forward
The concerning query() you will need to pass the list of dictionary as optional argument in the method signature
Final step is on the data provider side that has to implement the list of dictionary in the DB query, The CQL python module / plugin can also contain classes/methods/code that could help on the task, but for the data query to be efficient it has to be at data provider`

**Comment by jorgejesus** [comment]
@FarheenB  @francbartoli 

Checked the code and it holds, using breakpoints on `pytest` got a good overview of `pycql` and how things integrate.

-  CSV filtering is done here `https://github.com/FarheenB/pygeoapi/blob/a9d53f74f2364afc3dea1d56f2dac87b25ebe70e/pygeoapi/provider/csv_.py#L113`.  From a loaded dict from the CSV
-  Turning the `CQLFilterEvaluator` to integrate into the different data providers will be hard, for example for postgis we will need to generate an SQL statement, since we are not using ORM.  I am concern about `mapping` between pycql and the DB. 
- Worst case scenario would be loading the dict from the DB and then implement the CQL (not efficient)
-  The CQL plugin will have to aware what provider is using it and what should be the expected outcome, SQL, dict mapping etc
- IMHO, we should focus until the GSoC (now), on having a full working example, starting pygeoapi server and run a URL `https://localhost:5000/collections/obs/items?expression_filter="resulid<>355" `

**Comment by FarheenB** [comment]
@jorgejesus @francbartoli 

Files changed:

- pygeoapi/api.py- added section of code to check for CQL filter validity. If no exception raised then proceed to pygeoapi provider to evaluate query parameters. CQL filter has to be sent as a query parameter to the data providers. It cannot be executed as a plugin because parameters even have limit and startindex as queries which is evaluated inside the data providers. So CQL filter needs evaluation before limit is applied on the feature datase.

- pygeoapi/provider/csv_.py and pygeoapi/provider/geojson.py restructured a generic code base to parse CQL query filter and get filtered feature set in JSON. Implemented code for `result-type=hits` and `result-type=results`. Added code to get accurate `numberMatched` and `numberReturned` values after applying CQL filter.

- pygeoapi/cql_evaluate.py Now checks for CQL filter validity too

- pygeoapi/filters.py Added definition for evaluating **BetweenPredicateNode, InPredicateNode** and **NullPredicateNodes**.

- pygeoapi/util.py Added a function to get all the key fields of feature set on which filters can be performed.

- tests/test_csv__provider.py Added more unit test cases related to between, in, null operators and conditional expressions along with limit, start-index and result-type query parameters.


To Do:

- GeoJSON Test file needs restructuring so that CQL unit test cases can be added
- Decision needed on cql-lang query parameter
- Approach to be decided on temporal and spatial CQL complex filters
- How to check whether a data provider supports CQL filter or not.
- Add configuration of remaining data providers in config file, currently `obs` resource supports CSV and `lakes` supports GeoJSON in pygeoapi-config.yml file
  
Relevant Screenshots:

Test Cases for CSV Data provider-

![image](https://user-images.githubusercontent.com/59408650/89132436-c39a3b00-d531-11ea-8a56-31f4a0a607e5.png)

Endpoint for CSV Data-

![image](https://user-images.githubusercontent.com/59408650/89132515-5e931500-d532-11ea-9bcd-3b94abb5ab76.png)

![image](https://user-images.githubusercontent.com/59408650/89132523-723e7b80-d532-11ea-909d-a20137b7c9f2.png)

Output:

![image](https://user-images.githubusercontent.com/59408650/89132553-aade5500-d532-11ea-9bd4-7c3c026b7273.png)

Endpoint for GeoJSON Data-

![image](https://user-images.githubusercontent.com/59408650/89132592-f7299500-d532-11ea-893b-d3b693c37b1b.png)

![image](https://user-images.githubusercontent.com/59408650/89132617-25a77000-d533-11ea-840a-0967dcfa4146.png)

Output:

![image](https://user-images.githubusercontent.com/59408650/89132661-643d2a80-d533-11ea-8a49-cf0851fbbced.png)

![image](https://user-images.githubusercontent.com/59408650/89132678-88990700-d533-11ea-9999-dcc89320a0f3.png)

**Comment by FarheenB** [comment]
@jorgejesus @francbartoli Please check this https://github.com/FarheenB/pygeoapi/commit/8ad3f593435ecacef7a324aea157fee912efbb59 I have restructured the code of evaluating filters. Removed the loops and condition checking with lambda expressions to make the execution of multiple operations faster and the code more compact and concise.

**Comment by jorgejesus** [comment]
@francbartoli 
@FarheenB  Concerning the plugin implementation, for example on the CSV provider you can do:

```
from pygeoapi.plugin import load_plugin, PLUGINS
```

And then try to import `CQLParser, CQLFilterEvaluator` from the as  plugin, maybe I am missing something?

**Comment by FarheenB** [comment]
I can do this. But `CQLParser` and `CQLFilterEvaluator` are imported in each provider. If I change it to plugin structure then I will need to import plugins insider the providers. Will that work?

**Comment by FarheenB** [comment]
> @francbartoli
> @FarheenB Concerning the plugin implementation, for example on the CSV provider you can do:
> 
> ```
> from pygeoapi.plugin import load_plugin, PLUGINS
> ```
> 
> And then try to import `CQLParser, CQLFilterEvaluator` from the as plugin, maybe I am missing something?

I can do this. But CQLParser and CQLFilterEvaluator are imported in each provider. If I change it to plugin structure then I will need to import plugins insider the providers. Will that work?

**Comment by jorgejesus** [comment]
I expect for it to work,  it should be like importing a class

**Comment by FarheenB** [comment]
ok i will do it.

**Comment by FarheenB** [comment]
@jorgejesus am replying here as I need @francbartoli inputs in it too
> I have a question, what is the issue with  "Decision needed on cql-lang query parameter" ?

- According to my understanding `cql-lang` specifies the language in which filter parameter should be given as query. Refering to the OGC document default value of `cql-lang` should be `text` but type should be enum of `text` and `json`, so taht anyone of the options can be selected. 
- Present pygeoapi code base is working fine with `cql-text` as pycql parser and lexer takes text expression as input to form AST.
- If the cql-lang is changed to `json` then we will be needing an approach to convert `json` to normal `text` expression, so that it can be parsed by pycql module correctly.
- Following is the config structure of a resource that supports **cql filter**:

![image](https://user-images.githubusercontent.com/59408650/89714455-777d4980-d9bc-11ea-9c18-e14a8d553ee3.png)

**Comment by FarheenB** [comment]
> @FarheenB: I expect for it to work, it should be like importing a class, it will requrire that you create a plugin like you have for `provider`, `formatter`

I hope I got your requirements correct please check https://github.com/FarheenB/pygeoapi/commit/f17faf8d32d39f572d505836f79fc32a8fdf622f

**Comment by francbartoli** [comment]
> @jorgejesus am replying here as I need @francbartoli inputs in it too
> 
> > I have a question, what is the issue with  "Decision needed on cql-lang query parameter" ?
> 
> * According to my understanding `cql-lang` specifies the language in which filter parameter should be given as query. Referring to the OGC document default value of `cql-lang` should be `text` but type should be enum of `text` and `json`, so that any one of the options can be selected.
> * Present pygeoapi code base is working fine with `cql-text` as pycql parser and lexer takes text expression as input to form AST.
> * If the cql-lang is changed to `json` then we will be needing an approach to convert `json` to normal `text` expression, so that it can be parsed by pycql module correctly.
> * Following is the config structure of a resource that supports **cql filter**:
> 
> ![image](https://user-images.githubusercontent.com/59408650/89714455-777d4980-d9bc-11ea-9c18-e14a8d553ee3.png)

I've just commented on the issue discussion, see the most recent here https://github.com/geopython/pygeoapi/pull/478#discussion_r450892211

**Comment by FarheenB** [comment]
> > @jorgejesus am replying here as I need @francbartoli inputs in it too
> > > I have a question, what is the issue with  "Decision needed on cql-lang query parameter" ?
> > 
> > 
> > 
> > * According to my understanding `cql-lang` specifies the language in which filter parameter should be given as query. Referring to the OGC document default value of `cql-lang` should be `text` but type should be enum of `text` and `json`, so that any one of the options can be selected.
> > * Present pygeoapi code base is working fine with `cql-text` as pycql parser and lexer takes text expression as input to form AST.
> > * If the cql-lang is changed to `json` then we will be needing an approach to convert `json` to normal `text` expression, so that it can be parsed by pycql module correctly.
> > * Following is the config structure of a resource that supports **cql filter**:
> > 
> > ![image](https://user-images.githubusercontent.com/59408650/89714455-777d4980-d9bc-11ea-9c18-e14a8d553ee3.png)
> 
> I've just commented on the issue discussion, see the most recent here [#478 (comment)](https://github.com/geopython/pygeoapi/pull/478#discussion_r450892211)

@francbartoli  Yes I explained to @jorgejesus that `filters` key in config is not at provider level. It is at the resource level as per our previous discussions.

**Comment by francbartoli** [comment]
Ok can you now implement like the proposal in my comment if @jorgejesus agrees?

**Comment by jorgejesus** [comment]
@FarheenB  and @FarheenB  I do agree with filters being at provider level

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus According to my understanding I have made all the necessary changes for CQL to work at provider level.  The openapi document is now dependent on provider's support for CQL filters in a collection. Also added option for different filter language. Please leave comments. https://github.com/FarheenB/pygeoapi/commit/0463f29b08f7ac385daca40a90b4d43b7fec8ac2
