### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by aprilmay** [geopython/pygeoapi#529]
**Is your feature request related to a problem? Please describe.**
Pygeoapi already has support for Starlette, and other Asyncio frameworks gain momentum. However, the API is not async, blocking the main thread. 

**Describe the solution you'd like**
Provide an async version of pygeoapi.api

**Additional context**
A quick and dirty async prototype of pygeoapi's API was forked (for a project which uses aiohttp).

If it makes sense, what's the best way to proceed to add this? I'm thinking of an async_api module that could be used like in `from pygeopai.async_api import API`.

**Comment by francbartoli** [comment]
Hi @aprilmay, this would be great. It was in my todo list since ever. I think your approach makes sense.
However, I want just to flag that still the providers would block the thread because they are not async ready. Maybe you can start with the Postgres provider which would have some options for the async stuff.
