### ISSUE TITLE
/<collection>/items template renders property in wrong column

### ISSUE THREAD

**Issue by EHJ-52n** [geopython/pygeoapi#772]
### Problem

The last item`s **keywords** are rendered in the wrong column because it has not the following properties: **project** and **category**.

![screenshot_2021-09-09_13-39](https://user-images.githubusercontent.com/3839896/132679296-33051edc-f48d-43db-9428-a5a1567d24ec.png)

### Expected behavior

For all items in my catalog collection, the available properties are rendered in the html table.

### Implemented behavior

The property keys from the first item are used as headings:

https://github.com/geopython/pygeoapi/blob/774ff49f0060858fe3bec4d3ea73a970906baa6e/pygeoapi/templates/collections/items/index.html#L83-L88

The first 5 property columns of each item are shown. 

https://github.com/geopython/pygeoapi/blob/774ff49f0060858fe3bec4d3ea73a970906baa6e/pygeoapi/templates/collections/items/index.html#L92-L107

### Potential Solution

Collect list of available properties beforehand and add `None` if the property is not available for the current item in the for loop.

**Comment by frafra** [comment]
I can confirm that. It is rather annoying. The problem is that the provider could return a different number of properties for each item, and the header of the table looks at the first item only. This means that sources with a variable number of attributes will break for sure.

The list of columns should be computed before, based on all the entries that are going to be shown, and the cells should be generated based on that.
