### ISSUE TITLE
Add NetCDF and COG output types for EDR.

### ISSUE THREAD

**Issue by dblodgett-usgs** [geopython/pygeoapi#808]
This will require some planning and implementation.

The ability to return NetCDF and GeoTIFF files would be a valuable addition to the EDR provider. Shane Mill (NOAA) has a prototype. 

Closure Criteria: When the EDR Xarray provider can output geotiff and netcdf outputs and an initial pattern for implementing these outputs in other/new EDR providers is established.

**Comment by ShaneMill1** [comment]
NetCDF is relatively straightforward once you have the data in an xarray dataset object. You can output to netcdf using the to_netcdf function:

http://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_netcdf.html

Specifically with GRIB data, your netcdf file should be CF compliant if you use the cfgrib engine to open the GRIB file.

For Cloud Optimized GeoTiff, I used the datacube module and the to_cog function (to translate xarray object to COG):
https://datacube-core.readthedocs.io/en/stable/dev/api/generate/datacube.utils.cog.to_cog.html

The interesting thing here is when you have multidimensional data, COG may not be the most optimal format because I believe to_cog only supports 2D or 3D writing of data. For x,y,z,t you would have to create multiple COG files.

I am wondering if rasterio/rio can convert xarray objects to COG as well? Might be worth looking into
