### ISSUE TITLE
Spatial Filter via the map (How to link the geometries of the features shown in the current bounding box along with their properties?)

### ISSUE THREAD

**Issue by ThibautAr** [geopython/pygeoapi#851]
Hello,

I would like to know if there is a way to link the data shown on the bounding box (left) with their properties (right).
For instance, for the attached image, I would like to have only three rows (right) showing the properties of the three features (left).

![image](https://user-images.githubusercontent.com/98975549/152532355-b6d00359-9066-494e-9dd4-40e058a86103.png)

I'm guessing that it should be in [https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/collections/items/index.html](url) but I don't know what/where to modify.

Thanks

**Comment by pvgenuchten** [comment]
on the zoom-in/out event; we would need to update the url of the page to include &bounds={new bounds}

**Comment by francbartoli** [comment]
Sorry if I jump in and don't know if you have already considered this potential issue but the specification states that f=json and f=html should provide different view formats of the same data underneath.
So in practice, the template could be potentially considered a static view despite the zoom functionality.
Otherwise, it could look like the HTML view is diverging from this principle and behaves as an application per se rather than as an API view
