### ISSUE TITLE
Feature representation is expected to have ID (capitalized) field

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#94]
This concerns in particular the templates for HTML rendering of `items` like [here](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/items.html). 

## Problem
Some of the code in `PyGeoAPI`relies on the fact that a Feature has an id-field named `'ID'`. IMHO the [GeoJSON standard specifies](https://tools.ietf.org/html/rfc7946#section-3.2)  `'id'` (lowercase) as Id-field:

      If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or number

## Proposed Changes 
Ok, we are dealing with an internal representation, but since some formatting is automated I propose to use the name `id` all over or at least some indirection i.s.o. of hard-coding `ID`..

**Comment by pvgenuchten** [comment]
I added ft.ID in https://github.com/geopython/pygeoapi/blob/ca5c3fd5b486f8097d7a5470976c9fc04b614c98/pygeoapi/templates/items.html#L41, because in the example I used (obs) ID is in capitals. I agree, would be good to not allow different cases. Using lowercase 'id' seems suggested by standard. Let me create a PR for the fix on the html, but note that it should also be implemented on all json writers.
