### ISSUE TITLE
py conventions for trailing slash management

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#97]
I noticed sometimes users arrive in collections/obs/items and sometimes at collections/obs/items/. Both url's provide a valid answer however browsers treat both url's different when linking relatively. From these locations a '..' link will guide users to /collections in case 1 and to /collections/obs in case 2 

Some 'solutions'
- do not use relative links, always link to a full url
- check all links for consistency on adding the trailing slash (or not)
- auto-remove/add a trailing slash if detected it is not added (rewrite rule)

**Comment by pvgenuchten** [comment]
@justb4 part of this seems solved by #103, should we close this, or can it still be relevant in other scenario's?

**Comment by justb4** [comment]
@pvgenuchten think this can be closed as indicated above. you can try on http://geo.kralidis.ca/pygeoapi which runs current master branch.

**Comment by pvgenuchten** [comment]
i want to reopen this issue, because we seem to be incompatible with stac

i'm not aware if common/features/records has any recommendation on trainling slash

stac seems to require a trailing slash, https://github.com/radiantearth/stac-browser/issues/384

our behaviour: 
- https://demo.pygeoapi.io/master/collections/dutch_castles
- https://demo.pygeoapi.io/master/collections/dutch_castles/

**Comment by pvgenuchten** [comment]
Comments from Clemens Portele on discord:
- if you use a trailing slash, it is a different URI. In OGC API the resources do not have a trailing slash, which - from my experience - is the more common approach in APIs.
- Just look at the paths that are specified in the standards. None of them has a trailing slash. 
(Caveat: Strictly, you could argue that the Landing Page is an exception where the path is stated as "/", but this is a side effect from OpenAPI where all paths MUST start with a slash. It is not the intention that the Landing Page URI has a slash at the end.)

**Comment by dblodgett-usgs** [comment]
@pvgenuchten, @webb-ben, @tomkralidis -- I feel I may have stumbled into a hornets nest? 

https://github.com/radiantearth/stac-browser/issues/486#issuecomment-2414658587

Is there any way around this issue that will satisfy both OGC-API and STAC or is the issue of trailing slashes a point of divergence and incompatibility?

**Comment by pvgenuchten** [comment]
I guess the second:

> the issue of trailing slashes is a point of divergence and incompatibility

**Comment by m-mohr** [comment]
Wrong guess. There should not be any divergence and incompatibility. Resolving relative URIs is well-defined. Either an implementation is following RFC 3986 or not. STAC and OGC APIs must follow RFC 3986, otherweise they are pretty much unusable because the URIs are ambiguous and can't be resolved properly.

**Comment by ksonda** [comment]
I'll admit I don't know STAC exactly, but the consistent-uri guidance underscores the issue: `To avoid issues it is recommended to consistently add a slash at the end of the URL if it doesn't point to a file.`

OGC-API Features (and Common) `./collections` is a resource, whereas `./collections/` could be a construed as base URI for specific collections (and constituent items). However, in all extant documentation `/collections` selflink, and its target URL in other links is defined in the OGC API Feature spec as a resource, which thus is not supposed to be a base URI. [Consittuent items of collections are advised to link to /collections not /collections/](https://docs.ogc.org/is/17-069r4/17-069r4.html#_response_6). So, I don't think its as simple as "conform to IETF RFC 3986", since the OGC-API Features spec would seem to be in contradiction to it, and as a humble manager of developers who contribute to pygeoapi, would not know to point people to RFC 3986, but would know to point people to OGC specs, and would look to the OGC to ensure their standards comply with such things if they are essential to interoperability.

**Comment by ksonda** [comment]
I'll admit I don't know STAC exactly, but the consistent-uri guidance underscores the issue: `To avoid issues it is recommended to consistently add a slash at the end of the URL if it doesn't point to a file.`

OGC-API Features (and Common) `./collections` is a resource (one could say, a file), whereas `./collections/` could be a construed as base URI for specific collections (and constituent items). However, in all extant documentation `/collections` selflink, and its target URL in other links is defined in the OGC API Feature spec as a resource, which thus is not supposed to be a base URI. Basically, "base URI" does not seem to be a thing that can be communicated to clients consistently in servers implementing OGC API specs. For example, constituent items of collections are advised to link to `/collections/{collectionId}` not `/collections/{collectionsId}/` [See Example 14](https://docs.ogc.org/is/17-069r4/17-069r4.html#_requirements_class_geojson). So, I don't think its as simple as "conform to IETF RFC 3986", since the OGC-API Features spec would seem to be in contradiction and/or agnostic to it, and as a humble manager of developers who contribute to pygeoapi, would not know to point people to RFC 3986, but would know to point people to OGC specs, and would look to the OGC to ensure their standards support compliance with such things if they are essential to interoperability.

**Comment by dblodgett-usgs** [comment]
Not sure how to interpret a thumbs down... but I think it is worth being clear here and teasing this apart more than that. 

It seems that there are two interpretations of how OGC-API links should be constructed from a geojson feature collection.

On one hand, the `id` of a geojson feature within a geojson feature collection can be interpreted as a relative url where `self` is thought to be the base url. In this context, we would expect the overall geojson document to conform to [IETF RFC 3896](https://tools.ietf.org/rfc/rfc3896.txt). So we would expect trailing slashes on `self` even though the OGC-API spec does not include trailing slashes on paths or we would expect geojson `ids` to be valid relative url fragments, something they are not thought to be in common usage.  

On the other hand, the `id` of a geojson feature is a API-instance-scoped `id` of a feature that can be used according to the OGC-API Features convention for constructing a [get item by id request](https://docs.ogc.org/is/17-069r4/17-069r4.html#_feature_). In this context, we would expect client software to have knowledge of the path template `/collections/{collectionId}/items/{featureId}` in requirement 33A of OGC API Features where, according to requirement 33B, `{featureId}` is, _"`featureId` is the local identifier of the feature."_

This is why I was asking about the use of the OGC-API Common "conformance" document. Since stac-browser is querying for conformance information, it should know that some servers that do not return an indication of STAC conformance but do indicate that they adhere to OGC-API Features will likely adhere to the latter interpretation of how geojson `id` should be bound to a url. 

Am I off base here? I'm concerned that we are pushing the IETF URL construction standard into a place that it is not intended to apply.

**Comment by tomkralidis** [comment]
I would suggest we bring this up at OGC API - Common or Features as a next step.

**Comment by dblodgett-usgs** [comment]
Scanning issues -- this one pops up. https://github.com/opengeospatial/ogcapi-features/issues/918 

Any others that folks see that may have discussed this issue previously?

**Comment by m-mohr** [comment]
I don't think everyone here has an understanding of RFC 3896 at this point as the discussion is around Features, feature IDs and trailing slashes in self links etc, which is all pretty irrelevant, I think.

It is all about how to resolve a relative link against a base URL. How that's done is described in RFC3896.

It's pretty simple. Let say you have a Feature at https://example.com/collections/123/items/321 and you want to have a link from the collection 123 to that feature, using a self-links and a relative link. You have two options (you can omit the `./`):

1. self url: `https://example.com/collection/123`, relative URL to the feature: `./123/items/321`
2. self url: `https://example.com/collection/123/`, relative URL to the feature: `./items/321`

That are your options. I don't care whether you do 1 or 2, as long as it complies to RFC 3986.

The following is **invalid** according to the RFC:
- self url:  https://example.com/collection/123, relative URL to the feature: ./items/321

I'm actually not sure what to discuss here. Follow the RFC or accept that your API can't be properly handled by clients because the URL resolving is ambiguos/invalid. 🤷‍♂️

**Comment by dblodgett-usgs** [comment]
The discussion is that the convention we are using (OGC-API Features) doesn't actually say that there should be a relative URL encoded in hypermedia from `https://example.com/collection/123` to `https://example.com/collections/123/items/321` at all. 

The url template: `/collections/{collectionId}/items/{featureId}` is a convention of the API specification that must be constructed by a client application with knowledge of the API rather than by hydermedia url construction that would be governed by RFC3986. 

So for example, we look here:

`https://demo.pygeoapi.io/master/collections/lakes?f=json` and can follow the absolute link to `https://demo.pygeoapi.io/master/collections/lakes/items?f=json`

Notice that the links in the `items` response does not include links to individual `items`. The featureId must be retrieved from the geojson `id` -- which is not a relative url and, by that token, should not be subject to RFC3986 URL rules.

Notice that if we give the example collection of lakes to stac-browser we do get tiles for each lake. 
> https://radiantearth.github.io/stac-browser/#/external/demo.pygeoapi.io/master/collections/lakes?f=json

But if we click a link, the geojson id (not a relative url) is put into a url that drops the collection id in `/collections/{collectionId}/items/{featureId}`. 

@webb-ben made a modification to https://reference.geoconnex.us/ which adds a trailing slash to urls such as:

`https://reference.geoconnex.us/collections/hu02/?f=jsonld` which was `https://reference.geoconnex.us/collections/hu02?f=jsonld`

e.g. https://radiantearth.github.io/stac-browser/#/external/reference.geoconnex.us/collections/hu02/?f=json&.language=en 

Which does get stac-browser to template the url as would be expected. But I still feel like we are pushing RFC3986 rules into an area (geojson IDs) where it shouldn't necessarily be thought to apply dogmatically. 

Am I just missing where a relative URL actually exists in these documents? I feel like I'm just not seeing something here.
